"""
Long PII and dummy prompts for SafeKV ablation study.

Target: >= 4096 tokens per prompt so that:
  - Cold prefill cost ≈ 0.37s  (at ~11 k tok/s on Qwen3-32B TP=2 H100)
  - Cold TTFT ≈ 0.59 s  (prefill + 0.22 s scheduling overhead)
  - Hot TTFT (cache hit) ≈ 0.22 s  (scheduling only, no prefill)
  - probe/cold ratio ≈ 0.37  <<  0.80 threshold → attack clearly detectable

Each DUMMY_PROMPTS_BASE[i] is the same approximate length as PII_PROMPTS[i]
so the cold-baseline TTFT in Phase 5 reflects the same prefill cost as a
cache-miss on the victim's prompt.
"""

# ---------------------------------------------------------------------------
# PII prompts — each victim "owns" one.  ~4000-5000 tokens each.
# ---------------------------------------------------------------------------
PII_PROMPTS = [

    # ── Victim 0 : Medical record ──────────────────────────────────────────
    (
        "Please review my complete medical history, current medications, recent laboratory results, "
        "and all specialist notes, then provide detailed recommendations for optimizing my care. "
        "\n\n"
        "PATIENT IDENTIFICATION\n"
        "Full legal name: John Michael Smith. Date of birth: March 15, 1985. Age: 39 years. "
        "Gender: Male. Height: 5 ft 11 in (180 cm). Weight: 218 lb (98.9 kg). BMI: 30.4 (Class I Obesity). "
        "Race/Ethnicity: Caucasian, Non-Hispanic. Blood type: O positive. Preferred language: English. "
        "Medical record number: MRN-2024-087432. Social Security Number: 123-45-6789. "
        "Driver's license: TX-DL-83921047. Passport number: US-839201847, expires 2031. "
        "Home address: 4521 Westlake Drive, Austin, Texas 78746. "
        "Cell phone: 512-555-0192. Home phone: 512-234-5678. Work phone: 512-555-0300 ext 417. "
        "Email: jsmith1985@email.com. Employer: Austin Technology Solutions, 2100 Commerce St, Austin TX 78701. "
        "Emergency contact 1: Jane Ann Smith (wife), cell 512-234-9876, email janesmith@email.com. "
        "Emergency contact 2: Robert David Smith (father), cell 512-888-3421. "
        "\n\n"
        "INSURANCE\n"
        "Primary: BlueCross BlueShield of Texas. Policy BCB-TX-8834729. Group GRP-49302. "
        "Member ID MBR-334421-A. Subscriber: John Michael Smith, DOB 03/15/1985. "
        "Effective 01/01/2022. Copay: $30 PCP / $60 specialist / $150 ER. "
        "Individual deductible $1,500 (met $1,200 YTD). Family deductible $3,000. "
        "OOP max $6,000 individual / $12,000 family. "
        "Secondary: Aetna Supplemental. Policy AET-SUPP-7829031. Member ID AET-SM-334421. "
        "Dental: Delta Dental. Policy DDTX-88291034. Vision: VSP. Policy VSP-2024-334421. "
        "\n\n"
        "PRIMARY CARE PHYSICIAN\n"
        "Dr. Sarah Johnson MD. Specialty: Family Medicine. License: MD-TX-234567. NPI: 1928374650. "
        "Clinic: Austin Family Health Center, 3920 Medical Parkway, Austin TX 78756. "
        "Phone: 512-555-0192. Fax: 512-555-0193. "
        "\n\n"
        "ACTIVE PROBLEM LIST\n"
        "1. Type 2 Diabetes Mellitus (ICD-10 E11.9) — Diagnosed January 2019 by Dr. Johnson. "
        "Initial presentation: polydipsia, polyuria, fasting glucose 187 mg/dL, HbA1c 8.1%. "
        "Started Metformin 500mg twice daily, titrated to 1000mg twice daily by June 2019. "
        "Added Ozempic (semaglutide) 0.5mg weekly October 2023, titrated to 1.0mg weekly January 2024. "
        "Current HbA1c 7.2% (November 2024). Target <7.0%. Patient not meeting target. "
        "Complications screened: mild microalbuminuria detected (ACR 38 mg/g), no retinopathy, no neuropathy on monofilament. "
        "eGFR trending down: 81 (2022) → 76 (2023) → 72 (2024), CKD Stage G2 monitoring initiated. "
        "\n"
        "2. Essential Hypertension (I10) — Diagnosed March 2020. Initial BP 152/96 mmHg. "
        "Started Lisinopril 5mg, titrated to 10mg daily by June 2020. "
        "Current BP 138/88 mmHg (November 2024). Target <130/80. Not meeting target. "
        "ABPM performed August 2024: daytime average 141/90, nighttime 129/81, non-dipping pattern. "
        "\n"
        "3. Hyperlipidemia (E78.5) — Diagnosed July 2021. LDL 162 mg/dL at diagnosis. "
        "Started Atorvastatin 20mg, increased to 40mg December 2021. "
        "Current LDL 112 mg/dL. Target <100 mg/dL (high cardiovascular risk per ACC/AHA). "
        "Triglycerides elevated at 189 mg/dL. HDL 48 mg/dL. "
        "\n"
        "4. Obesity, Class I (E66.09) — BMI 30.4. Weight has increased 14 lb since 2021. "
        "Referred to registered dietitian June 2023 (Lisa Park RD, Austin Nutrition Center). "
        "Completed 8 nutrition counseling sessions. Ongoing lifestyle modification counseling. "
        "\n"
        "5. Vitamin D Deficiency (E55.9) — Diagnosed April 2022. Initial level 14 ng/mL. "
        "On Vitamin D3 2000 IU daily. Current level 28 ng/mL (November 2024). Target >30 ng/mL. "
        "\n"
        "6. Obstructive Sleep Apnea, mild (G47.33) — Diagnosed September 2022. "
        "AHI 12 events/hour, O2 nadir 88%, predominantly REM-related events. "
        "CPAP 8 cmH2O prescribed (ResMed AirSense 11, S/N 23-882-91034). "
        "Compliance: 68% nights. Average AHI on treatment 2.3 events/hour on compliant nights. "
        "\n"
        "7. Gastroesophageal Reflux Disease (K21.0) — Diagnosed February 2023. "
        "Symptoms: heartburn, regurgitation after meals. On Omeprazole 20mg daily. Well-controlled. "
        "Upper endoscopy deferred (no alarm symptoms). "
        "\n"
        "8. Generalized Anxiety Disorder (F41.1) — Diagnosed October 2023. "
        "PHQ-9 score 8 (moderate) at diagnosis. GAD-7 score 11. "
        "Started Sertraline 25mg, titrated to 50mg. Current PHQ-9 4, GAD-7 6. "
        "Follows with Dr. Kira Patel PhD monthly (cognitive behavioral therapy). "
        "\n"
        "9. Chronic Low Back Pain (M54.5) — History since 2018 lumbar strain. "
        "Lumbar MRI (April 2022): L4-L5 disc bulge mild, no nerve root compression, no stenosis. "
        "Completed 24 sessions physical therapy January-August 2024 (Austin PT and Spine Center). "
        "Currently using NSAIDs PRN; last flare October 2024. "
        "\n"
        "10. Borderline microalbuminuria / early CKD G2 (N18.2) — new problem flagged November 2024. "
        "ACR 38 mg/g. eGFR 72. Repeat ACR in 3 months. Nephrology referral discussed. "
        "\n\n"
        "CURRENT MEDICATIONS (November 2024)\n"
        "1. Metformin HCl (Glucophage) 1000 mg oral tablet — 1 tab PO BID with meals. "
        "For T2DM. Prescriber: Dr. Johnson. Pharmacy: CVS #1847, 4500 Research Blvd Austin TX 78759. "
        "Rx# RX-2024-083921. Last filled 11/01/2024, 60 tabs, 30-day supply. "
        "2. Lisinopril 10 mg oral tablet — 1 tab PO QD every morning. "
        "For hypertension. Rx# RX-2024-083922. Last filled 11/01/2024. "
        "3. Atorvastatin calcium (Lipitor) 40 mg — 1 tab PO QD at bedtime. "
        "For hyperlipidemia. Rx# RX-2024-083923. Last filled 11/01/2024. "
        "4. Semaglutide (Ozempic) 1 mg/0.75 mL SC pen — inject 1 mg SC once weekly (Sundays). "
        "For T2DM. Rx# RX-2024-083924. Last filled 10/28/2024, 1 pen = 4 doses. "
        "5. Omeprazole 20 mg delayed-release capsule — 1 cap PO QD 30 min before breakfast. OTC. "
        "6. Sertraline HCl (Zoloft) 50 mg — 1 tab PO QD every morning. "
        "For GAD. Prescriber: Dr. Kira Patel PhD. Rx# RX-2024-078123. "
        "7. Vitamin D3 (cholecalciferol) 2000 IU softgel — 1 cap PO QD. OTC supplement. "
        "8. Aspirin 81 mg enteric coated — 1 tab PO QD with food. Cardiovascular prophylaxis. OTC. "
        "9. Melatonin 5 mg — 1 tab PO QHS PRN sleep, 30 min before bed. OTC. "
        "10. Ibuprofen 600 mg — 1 tab PO TID with food PRN low back pain. Max 5 consecutive days. OTC. "
        "\n\n"
        "ALLERGIES AND ADVERSE REACTIONS\n"
        "1. Penicillin — Anaphylaxis (throat edema, urticaria, hypotension, bronchospasm). "
        "Life-threatening. 1998 (age 13), reaction to Amoxicillin for strep pharyngitis. "
        "Hospitalized 2 days. Epipen prescribed. Cross-reactivity: all beta-lactam antibiotics flagged. "
        "2. Sulfonamides — Diffuse maculopapular rash, severe pruritus. Moderate. "
        "2012, reaction to Bactrim DS for UTI. "
        "3. Codeine — Severe nausea, vomiting, lightheadedness. Moderate. 2015 post-operative. "
        "4. Iodinated contrast — Mild urticaria, flushing. Mild. 2020 CT abdomen. "
        "Pre-medication protocol: Prednisone 50mg 13h, 7h, 1h prior + Diphenhydramine 50mg 1h prior. "
        "5. Latex — Contact urticaria. Mild. 2019. Latex-free gloves required. "
        "\n\n"
        "LABORATORY RESULTS\n"
        "Comprehensive Metabolic Panel — 11/14/2024: "
        "Na 139 / K 4.1 / Cl 102 / CO2 25 / BUN 18 / Cr 1.1 / eGFR 72 / "
        "Glucose fasting 142 (HIGH) / Ca 9.4 / Total protein 7.2 / Albumin 4.1 / "
        "Total bilirubin 0.9 / ALT 38 / AST 31 / Alk Phos 72. "
        "Prior CMP 11/2023: Na 140 / K 4.0 / BUN 16 / Cr 1.05 / eGFR 76 / Glucose 148. "
        "Prior CMP 11/2022: Na 141 / K 3.9 / BUN 15 / Cr 0.98 / eGFR 81 / Glucose 155. "
        "\n"
        "Lipid Panel — 11/14/2024: "
        "Total cholesterol 198 / LDL 112 (HIGH for high-risk) / HDL 48 / TG 189 (ELEVATED) / Non-HDL 150. "
        "Prior lipid 11/2023: TC 204 / LDL 118 / HDL 46 / TG 201. "
        "Prior lipid 07/2021 (pre-statin): TC 251 / LDL 162 / HDL 42 / TG 234. "
        "\n"
        "HbA1c and Diabetes — 11/14/2024: "
        "HbA1c 7.2% / eAG 160 mg/dL / Fasting glucose 142 / Urine ACR 38 mg/g (ELEVATED). "
        "Prior HbA1c: 07/2024: 7.4% / 01/2024: 7.1% / 07/2023: 7.6% / 01/2023: 7.8% / "
        "07/2022: 7.5% / 01/2022: 7.3% / 07/2021: 7.2% / 01/2021: 7.9% / 01/2020: 7.7% / 01/2019 (dx): 8.1%. "
        "\n"
        "CBC — 11/14/2024: WBC 7.2 / RBC 4.8 / Hgb 14.8 / Hct 43.2% / MCV 90 / Plt 224. All normal. "
        "Thyroid: TSH 2.3 (06/2024), Free T4 1.1. Normal. "
        "Vitamin D: 28 ng/mL (11/2024). Iron studies: Ferritin 82, TIBC 312, Iron 78. Normal. "
        "PSA: 1.2 ng/mL (10/2024). Age-appropriate. "
        "Urine microalbumin: 38 mg/g (11/2024), 22 mg/g (11/2023), 18 mg/g (11/2022). Trending up. "
        "\n\n"
        "SPECIALIST CONSULTATIONS\n"
        "Cardiology (Dr. Lisa Chen MD, Austin Cardiology Group, 512-555-0400): "
        "Echocardiogram March 2022 — mild LV hypertrophy (wall thickness 1.2 cm), EF 62%, "
        "no valvular pathology, grade 1 diastolic dysfunction. Recommendation: continue antihypertensives, "
        "recheck echo in 3 years. Stress test deferred (low pretest probability). "
        "ABPM August 2024: non-dipping pattern. Recommended adding amlodipine if BP remains above goal. "
        "\n"
        "Gastroenterology (Dr. Robert Hughes MD, GI Associates of Austin, 512-555-0500): "
        "Colonoscopy September 2023 — normal mucosa throughout, no polyps, adequate prep. "
        "Next colonoscopy recommended age 49 (10 years). H. pylori testing negative. "
        "\n"
        "Sleep Medicine (Austin Sleep Center, 512-555-0600): "
        "Sleep study September 2022 — AHI 12, O2 nadir 88%, predominantly REM events. "
        "CPAP prescribed. 6-month follow-up compliance 68%. Consider BiPAP if compliance remains low. "
        "\n"
        "Ophthalmology — Dr. Maria Santos OD (Austin Eye Associates, 512-555-0700): "
        "Dilated fundus exam October 2024 — no diabetic retinopathy, no macular edema. "
        "Annual screening recommended. "
        "\n"
        "Podiatry — Dr. David Lee DPM (512-555-0800): "
        "Diabetic foot exam October 2024 — monofilament sensation intact bilateral, "
        "no callus or ulceration, normal pulses. Annual exam. "
        "\n"
        "Behavioral Health — Dr. Kira Patel PhD (Austin Behavioral Health, 512-555-0900): "
        "Monthly CBT sessions ongoing since October 2023. PHQ-9 improved from 8 to 4. "
        "GAD-7 improved from 11 to 6. Continuation recommended. "
        "\n\n"
        "FAMILY HISTORY\n"
        "Father (Robert David Smith, age 68, Austin TX): Type 2 DM diagnosed age 52, "
        "hypertension since age 45, coronary artery disease, MI at age 61 (inferior STEMI), "
        "two-vessel CABG (LAD, RCA) June 2019, currently on aspirin 81 mg, metoprolol succinate 50 mg, "
        "lisinopril 10 mg, atorvastatin 80 mg, Plavix. Living. "
        "Mother (Patricia Ann Smith nee Williams, age 65, Austin TX): Hypertension (Amlodipine), "
        "hypothyroidism (Levothyroxine 75 mcg), osteoporosis (Alendronate weekly), DEXA T-score -2.6. Living. "
        "Paternal grandfather (Harold Smith): Died age 72, MI. "
        "Paternal grandmother (Eleanor Smith): Died age 80, congestive heart failure. "
        "Maternal grandfather (George Williams): Died age 68, stroke (CVA). "
        "Maternal grandmother (Ruth Williams): Living, age 91, dementia. "
        "Sister (Jennifer Smith, age 36, Houston TX): No known chronic conditions. "
        "No family history of colon cancer, prostate cancer, or inherited kidney disease. "
        "\n\n"
        "SOCIAL AND LIFESTYLE HISTORY\n"
        "Occupation: Senior software engineer, desk-based, works from home 3 days/week. "
        "Sedentary during work hours (5-9 hours seated). "
        "Tobacco: Never smoker. Former social smoker 2005-2010 (estimated <5 pack-years). "
        "Alcohol: Occasional. 2-4 standard drinks per week, primarily weekends. "
        "Cannabis: Denies. Recreational drugs: Denies. "
        "Physical activity: Walks 20-30 min 3×/week (mild intensity). No structured exercise. "
        "Diet: Mixed carbohydrate/protein. Fast food 2-3×/week (Chick-fil-A, Chipotle). "
        "Estimated daily caloric intake 2400-2800 kcal. High-sodium diet (patient endorses). "
        "Sleep: 6.5-7 hours nightly. CPAP use inconsistent. Reports fatigue despite sleep. "
        "Stress level: Self-reports 7/10. Major stressors: work deadlines, financial pressures. "
        "Marital status: Married 10 years to Jane Ann Smith (age 37). Two children: "
        "Michael Smith (age 10, Austin Elementary) and Emma Smith (age 8, Austin Elementary). "
        "\n\n"
        "REVIEW OF SYSTEMS (November 2024)\n"
        "Constitutional: Fatigue (moderate, ongoing), no fever, no night sweats, no unintentional weight loss. "
        "Weight stable ±3 lb past 6 months. "
        "Cardiovascular: No chest pain, no palpitations. Occasional exertional dyspnea on 2+ flights of stairs. "
        "Bilateral ankle edema mild in evenings. No syncope. "
        "Respiratory: No cough. Mild snoring per wife. CPAP use 68% nights. "
        "Gastrointestinal: GERD symptoms controlled on omeprazole. No dysphagia. "
        "Occasional constipation (2-3 BM/week). No rectal bleeding. "
        "Genitourinary: Nocturia 2-3×/night (NEW concern, previously 0-1×). "
        "No dysuria, no hematuria. Urine stream adequate. "
        "Musculoskeletal: Low back pain intermittent, rated 3-5/10. Worse with prolonged sitting. "
        "Morning stiffness <30 min. No joint swelling. "
        "Neurological: Bilateral foot tingling and numbness intermittently upon waking (NEW symptom). "
        "No headache. No vision changes. "
        "Endocrine: Polyuria, polydipsia mild. Heat intolerance mild. Cold intolerance none. "
        "Skin: No rash. Slow-healing paper cut on right index finger (2 weeks, healing). "
        "Psychiatric: Anxiety improved. Sleep quality fair. "
        "\n\n"
        "SPECIFIC QUESTIONS FOR PHYSICIAN REVIEW\n"
        "1. My HbA1c has been 7.0-7.5% for 18 months despite Metformin 1000mg BID and Ozempic 1mg weekly. "
        "Is my regimen adequate? Should I add a SGLT-2 inhibitor (Jardiance) which might also help my blood pressure and kidneys? "
        "2. My eGFR has declined from 81 (2022) to 72 (2024) and my urine ACR has risen to 38 mg/g. "
        "Do I need a nephrology referral now? Should I start a SGLT-2 inhibitor or ACE inhibitor dose increase? "
        "3. My LDL is 112 mg/dL, still above the <100 mg/dL target. Should I increase atorvastatin to 80mg, "
        "or add ezetimibe 10mg? My father had an MI at 61 and I want aggressive lipid management. "
        "4. My BP is 138/88 despite Lisinopril 10mg. The cardiologist mentioned possibly adding Amlodipine. "
        "My non-dipping ABPM pattern concerns me. Should I add Amlodipine 5mg? "
        "5. I have new nocturia 2-3×/night and bilateral foot tingling. Is this diabetic peripheral neuropathy "
        "beginning? What neuropathy screening should I undergo? "
        "6. My slow-healing finger cut concerns me. What wound care should I follow? "
        "7. My CPAP compliance is only 68%. What strategies would improve compliance? "
        "Please review all of the above and provide a prioritized care plan."
    ),

    # ── Victim 1 : Financial / banking fraud ─────────────────────────────
    (
        "I need urgent assistance reviewing and disputing fraudulent transactions across my financial accounts. "
        "Please review all account details and transaction history below and advise on immediate protective steps. "
        "\n\n"
        "PERSONAL IDENTIFICATION\n"
        "Full legal name: Emily Rose Thornton. Date of birth: July 22, 1990. Age: 34. "
        "Social Security Number: 987-65-4321. "
        "Driver's license: OR-DL-74829103. Passport: US-E92837461, expires September 2028. "
        "Home address: 892 Maple Avenue, Portland, Oregon 97201. "
        "Cell phone: 503-555-7842. Work phone: 503-555-9100 ext 234. "
        "Email: emily.thornton.1990@gmail.com. Alternate email: ethornton@workmail.com. "
        "Employer: Pacific Northwest Analytics LLC, 1200 SW 5th Ave, Portland OR 97204. "
        "Occupation: Senior data analyst. Salary approximately $118,000/year. "
        "Emergency contact: Daniel Thornton (husband), cell 503-555-2847. "
        "\n\n"
        "BANK ACCOUNTS — CHASE BANK\n"
        "Primary checking: Account number 000-4738291-7. Routing number 021000021. "
        "Current balance (as of 11/18/2024): $12,847.33. "
        "Average monthly balance: $9,200. Direct deposit: payroll every 15th and last day of month. "
        "Linked debit card: Visa ending 4729, expiry 08/27, CVV on card 341. "
        "\n"
        "Primary savings: Account number 000-9182736-4. Routing number 021000021. "
        "Current balance: $34,220.15. High-yield savings, 4.50% APY. "
        "Auto-transfer $500/month from checking. Goal: emergency fund (6 months expenses). "
        "\n"
        "Joint checking with husband (Daniel Thornton): Account number 000-2847362-1. "
        "Routing 021000021. Current balance $7,439.88. Used for household expenses. "
        "\n"
        "Chase Premier account (recently opened): Account number 000-8374920-5. "
        "Balance $250.00 (minimum to avoid fee). Opened November 2024. "
        "\n\n"
        "CREDIT CARDS\n"
        "Visa Signature (Chase Sapphire Preferred): Card number 4532-1234-5678-9010. "
        "Expiry 09/27. CVV 312. Credit limit $25,000. Current balance $4,891.22. "
        "Minimum payment $98. Due date 12/07/2024. "
        "Rewards: 487,200 Ultimate Rewards points (value ~$4,872 cash). "
        "\n"
        "Mastercard World Elite (Citi Double Cash): Card number 5412-8888-3333-7777. "
        "Expiry 04/26. CVV 918. Credit limit $15,000. Current balance $1,203.47. "
        "Due date 12/14/2024. "
        "\n"
        "American Express Gold: Card number 3782-800012-34567. Expiry 11/25. CID 4892. "
        "No preset spending limit. Current balance $2,318.90. "
        "Membership Rewards: 124,300 points. "
        "\n"
        "Discover It: Card number 6011-1111-2222-3333. Expiry 03/28. CVV 771. "
        "Credit limit $10,000. Balance $0.00. Paid in full each month. "
        "\n\n"
        "INVESTMENT AND RETIREMENT ACCOUNTS\n"
        "Fidelity brokerage: Account number 382-847291. "
        "Portfolio value: $128,430 (as of 11/15/2024). "
        "Holdings: 60% Fidelity 500 Index Fund (FXAIX), 20% Fidelity Total Market (FSKAX), "
        "10% Fidelity International (FSPSX), 10% Fidelity Bond Index (FXNAX). "
        "\n"
        "Fidelity 401(k) via employer: Account number 401K-PAC-ET90234. "
        "Balance: $89,321.44. 6% salary contribution + 4% employer match. "
        "\n"
        "Fidelity Roth IRA: Account number ROTH-382-847292. Balance: $43,180.22. "
        "Max contribution each year ($7,000 for 2024). "
        "\n"
        "Savings bonds: Series I bonds, purchased October 2022, face value $10,000, "
        "current value (estimated) $10,980 at current I-bond rate 4.28%. "
        "\n\n"
        "LOANS AND LIABILITIES\n"
        "Mortgage: Wells Fargo. Loan number WF-MTG-2019-00382741. "
        "Property: 892 Maple Avenue, Portland OR 97201. Appraised $645,000 (2024). "
        "Original loan: $450,000 at 3.25% fixed 30-year (2019). "
        "Remaining balance: $389,204.17. Monthly payment $1,957.42. "
        "\n"
        "Auto loan: Honda Financial Services. Loan number HFS-2022-0038274. "
        "Vehicle: 2022 Honda CR-V. Remaining balance: $18,920.44. "
        "Monthly payment: $498.00. Payoff date: March 2027. "
        "\n\n"
        "RECENT TRANSACTION HISTORY — PRIMARY CHECKING (Oct 26 — Nov 18, 2024)\n"
        "11/18 DEBIT  $2,340.00  MERCHANT-XK-9923  (UNKNOWN — flagged suspicious) "
        "11/18 DEBIT  $189.00    ONLINE-CASINO-77  (UNKNOWN — flagged suspicious) "
        "11/16 DEBIT  $78.50     GAS STATION PHOENIX AZ (unfamiliar location — suspicious) "
        "11/15 CREDIT $4,916.67  PNW ANALYTICS PAYROLL direct deposit "
        "11/14 DEBIT  $1,957.42  WELLS FARGO MORTGAGE autopay "
        "11/14 DEBIT  $498.00    HONDA FINANCIAL autopay "
        "11/12 DEBIT  $243.18    WHOLE FOODS PORTLAND OR "
        "11/10 DEBIT  $89.99     NETFLIX subscription "
        "11/09 DEBIT  $54.21     PGE PORTLAND electric bill "
        "11/07 DEBIT  $147.33    FRED MEYER Portland OR groceries "
        "11/05 DEBIT  $38.00     PLANET FITNESS Portland membership "
        "11/04 DEBIT  $112.47    AMAZON PRIME purchase "
        "11/01 DEBIT  $1,200.00  RENT PAYMENT (sister's loan) "
        "10/31 CREDIT $4,916.67  PNW ANALYTICS PAYROLL "
        "10/30 DEBIT  $67.89     TRADER JOE'S Portland OR "
        "10/28 DEBIT  $2,100.00  TRANSFER to savings account "
        "10/25 DEBIT  $339.94    COSTCO Portland OR "
        "10/22 DEBIT  $203.11    RESTAURANT/DINING Portland OR various "
        "10/20 DEBIT  $88.00     COMCAST internet bill "
        "10/18 DEBIT  $45.00     SPOTIFY family plan annual "
        "\n\n"
        "RECENT TRANSACTION HISTORY — CHASE SAPPHIRE PREFERRED (Oct — Nov 2024)\n"
        "11/17 CHARGE $1,847.00  TRAVEL MERCHANT UNKNOWN (suspicious, not recognized) "
        "11/14 CHARGE $289.44    ALASKA AIRLINES PDX tickets purchased by cardholder "
        "11/11 CHARGE $134.88    RESTAURANT PORTLAND OR (recognized) "
        "11/08 CHARGE $2,200.00  AMZN MKTP US (electronics — not recognized by cardholder) "
        "11/05 CHARGE $56.99     HULU subscription (recognized) "
        "11/01 CHARGE $449.00    HOTEL BOOKING Portland (recognized) "
        "10/29 CHARGE $78.33     FRED MEYER groceries (recognized) "
        "10/25 CHARGE $1,200.00  APPLE STORE ONLINE (not recognized — suspicious) "
        "\n\n"
        "TAX INFORMATION\n"
        "Filing status: Married Filing Jointly. "
        "2023 AGI: $247,800 (combined with Daniel). Federal taxes paid $41,240. "
        "State taxes (Oregon): $22,100 paid (9.9% bracket). "
        "Oregon refund 2023: $834 received April 2024. "
        "Estimated 2024 tax liability (self-assessed): similar to 2023. "
        "Tax preparer: TurboTax online, CPA review performed by Daniel Martinez CPA, "
        "Portland Tax Associates, 503-555-3300. "
        "\n\n"
        "PROPERTY AND ASSETS\n"
        "Primary residence: 892 Maple Avenue, Portland OR 97201. Appraised $645,000. "
        "Joint ownership with husband Daniel Thornton. Mortgage remaining $389,204. "
        "Net equity ~$255,796. "
        "Vehicle 1: 2022 Honda CR-V EX. VIN 2HKRW2H59NH123456. Lien (Honda Financial). "
        "Vehicle 2: 2020 Toyota Prius. VIN JTDKARFU9L3123456. Owned outright. KBB value ~$19,800. "
        "Jewelry: engagement ring appraised at $12,400. Insured under homeowners rider. "
        "\n\n"
        "SUSPICIOUS ACTIVITY SUMMARY\n"
        "I believe my accounts have been compromised. On November 16-18, I received three email "
        "notifications of transactions I did not authorize: "
        "1. $2,340 charge at MERCHANT-XK-9923 (I cannot identify this vendor anywhere online). "
        "2. $189 charge at ONLINE-CASINO-77 (I do not gamble online). "
        "3. $78.50 gas charge in Phoenix AZ (I have been in Portland all week, not Phoenix). "
        "Additionally, my Chase Sapphire shows: "
        "4. $1,847 at unknown travel merchant on 11/17. "
        "5. $2,200 Amazon purchase on 11/08 for electronics, shipped to a Miami FL address I do not recognize. "
        "6. $1,200 Apple Store Online on 10/25 for an iPhone 16 I never ordered. "
        "I have already frozen my debit card. I am concerned my email or online banking password was stolen. "
        "I received a suspicious phishing email from 'Chase-Security@chaase-alerts.net' on November 12 "
        "asking me to 'verify my account' — I did NOT click the link. "
        "Please advise on: (1) which charges are definitely fraudulent, (2) dispute process, "
        "(3) securing all accounts, (4) whether to file a police report, (5) identity theft monitoring."
    ),

    # ── Victim 2 : Immigration / legal ───────────────────────────────────
    (
        "I urgently need comprehensive immigration legal advice regarding my status, my pending green card, "
        "and my upcoming H-1B expiration. Please review all information and advise on every available option. "
        "\n\n"
        "PERSONAL INFORMATION\n"
        "Full legal name: Wei-Lin Chen (Chinese: 陈伟林). Date of birth: November 3, 1988. Age: 35. "
        "Gender: Male. Nationality: People's Republic of China. "
        "Passport number: E72938847. Issued: March 15, 2019. Expires: March 14, 2029. "
        "Place of issue: Shanghai, China. "
        "US Alien Registration Number (A-Number): A-293847162. "
        "Social Security Number: 629-38-4712 (issued December 2015 on F-1 OPT). "
        "Home address: 3847 Cherry Blossom Lane, Apt 204, Sunnyvale, California 94086. "
        "Cell phone: 669-555-0284. Work phone: 408-555-9200 ext 3847. "
        "Email: weilin.chen.dev@gmail.com. Alternate: wchen@datasystems.com. "
        "\n\n"
        "CURRENT IMMIGRATION STATUS\n"
        "Current status: H-1B specialty occupation worker. "
        "Current I-94 number: 83947201834. "
        "Admission date: October 15, 2022. "
        "Authorized until: October 14, 2025 (13 months remaining as of November 2024). "
        "Port of entry: San Francisco International Airport (SFO). "
        "Current H-1B employer: DataSystems Corp (petitioner). "
        "Employer address: 1200 Tech Blvd, San Jose, California 95110. "
        "Employer EIN: 94-3827461. "
        "USCIS receipt number for current H-1B: WAC2210038291. "
        "H-1B cap-exempt employer: No (cap-subject, lottery selected in April 2019). "
        "\n\n"
        "EMPLOYMENT HISTORY (US)\n"
        "Current: DataSystems Corp, San Jose CA. "
        "Title: Principal Software Engineer, Machine Learning Infrastructure. "
        "Salary: $198,000 base + $45,000 annual bonus + $80,000 RSU annual vesting. "
        "Start date: November 1, 2019. "
        "Sponsor status: H-1B sponsor and I-140 sponsor. "
        "\n"
        "Prior employer 1: TechStartup Inc, 500 Innovation Way, Palo Alto CA 94301. "
        "Title: Software Engineer. Salary $145,000. Dates: October 2015 — October 2019 (F-1 OPT + Cap-Gap). "
        "\n"
        "Prior employer 2 (internship): Google LLC, Mountain View CA. "
        "Dates: June 2014 — August 2014 (F-1 CPT). "
        "\n\n"
        "EDUCATION\n"
        "PhD, Computer Science — Stanford University, Stanford CA. "
        "Graduation: June 2015. Dissertation: 'Distributed Machine Learning Optimization.' "
        "I-20 school code: 001305. SEVIS ID: N0012947382. "
        "\n"
        "BS, Computer Science — Tsinghua University, Beijing, China. Graduation: June 2010. "
        "\n\n"
        "GREEN CARD PETITION DETAILS\n"
        "I-140 Immigration Petition for Alien Workers: "
        "Classification: EB-2 (National Interest Waiver self-petition). "
        "Receipt number: WAC2310048291. "
        "Filing date: August 14, 2023. "
        "Approval date: December 18, 2023. "
        "Priority date: February 14, 2020 (from an earlier employer-sponsored EB-2 PERM petition). "
        "\n"
        "Earlier employer-sponsored EB-2 PERM: "
        "TechStartup Inc PERM labor certification: DOL case number P-200-19027-437291. "
        "PERM approved: September 30, 2019. "
        "I-140 (employer-sponsored): Receipt WAC1910038471. "
        "Priority date established: February 14, 2020 (date of PERM filing). "
        "This I-140 was approved December 15, 2020 but later withdrawn by TechStartup when I changed employers. "
        "Priority date was preserved because I-140 was approved before withdrawal. "
        "\n"
        "Country of chargeability: China (Mainland Born). "
        "EB-2 China final action date (October 2024 Visa Bulletin): January 1, 2019. "
        "Priority date February 14, 2020 is NOT current (approximately 13 months behind). "
        "Estimated wait: 18-36 months before priority date becomes current, based on recent movement. "
        "\n\n"
        "FAMILY MEMBERS\n"
        "Spouse: Mei-Xuan Liu (Chinese: 刘美璇). Date of birth: August 17, 1990. "
        "Passport: F38291748 (PRC), expires April 2027. "
        "A-Number: A-389472019. SSN: 629-47-3821. "
        "Current status: H-4 dependent. I-94 number: 93847201928. Authorized until October 14, 2025. "
        "H-4 EAD (Employment Authorization Document): EAD number: MSC2290028374. "
        "EAD expiration: October 14, 2025 (tied to principal's H-1B). "
        "Employer: Stanford University Hospital, Palo Alto CA. "
        "Title: Research Coordinator. Salary: $72,000. "
        "\n"
        "Child 1: Jason Wei Chen. Date of birth: June 5, 2018, San Jose, California. "
        "US Citizen by birth. Passport: US-C84729103 (minor), expires June 2028. "
        "Does NOT require immigration status — is a US citizen. "
        "\n\n"
        "VISA AND TRAVEL HISTORY\n"
        "F-1 student visa first issued: September 10, 2010. Visa number F-1-2010-3847291. "
        "Entered US on F-1: September 15, 2010. "
        "OPT period: June 2015 — November 2015. STEM OPT extension: November 2015 — November 2018. "
        "Cap-Gap extension applied: April 2019 (maintained status through H-1B start October 1, 2019). "
        "H-1B first issued: October 1, 2019. "
        "H-1B extension filed: July 2022. Approved October 2022. "
        "\n"
        "International travel in last 5 years: "
        "China (Shanghai): December 2019 (2 weeks, returned January 2020). "
        "China (Beijing): December 2021 (10 days, returned January 2022). "
        "Canada (Toronto, business conference): March 2023 (5 days). "
        "UK (London, IEEE conference): September 2023 (7 days, returned on valid H-1B visa). "
        "\n\n"
        "CURRENT ISSUES AND URGENT CONCERNS\n"
        "1. H-1B EXPIRATION: My H-1B (and wife's H-4/H-4 EAD) expires October 14, 2025. "
        "DataSystems Corp has agreed to file an H-1B extension. "
        "What is the optimal timing to file? Can we use premium processing ($2,805)? "
        "If the extension is filed before October 14, 2025 (cap-gap does not apply — we're in H-1B status), "
        "does my wife's H-4 EAD automatically extend? "
        "\n"
        "2. PRIORITY DATE BACKLOG: My EB-2 China priority date of February 14, 2020, is not yet current "
        "(current date is January 1, 2019). At the current pace (~1-3 months movement per bulletin), "
        "I may wait 18-36 more months. "
        "Is there any strategy to accelerate this? Can I use the Dates for Filing (DFP) chart instead "
        "of the Final Action Date (FAD) chart? What does 'concurrent filing' mean in my situation? "
        "\n"
        "3. AC21 PORTABILITY: If DataSystems Corp is acquired or I want to change jobs, "
        "can I port my I-140 to a new employer under AC21 (180-day rule)? "
        "What conditions must be met? Does my new job need to be in the 'same or similar occupational classification'? "
        "\n"
        "4. EB-1A OPTION: Given my publication record (22 peer-reviewed papers, h-index 14, "
        "3 US patents, invited to review for NeurIPS and ICML), would I qualify for EB-1A "
        "extraordinary ability self-petition? This would bypass the country backlog. "
        "What evidence do I need to compile? "
        "\n"
        "5. O-1A BRIDGE OPTION: While awaiting green card, could I convert to O-1A status "
        "as an alternative if H-1B extension is delayed? "
        "\n"
        "6. MINOR CHILD'S CITIZENSHIP DOCUMENTATION: Jason was born in the US. "
        "I need to document his citizenship for a potential China trip in 2025. "
        "What Chinese documents does he need? Does he need a Chinese passport as well? "
        "Can he travel on only a US passport? "
        "\n"
        "Please provide a comprehensive strategy for maintaining legal status, "
        "optimizing my path to a green card, and protecting my family."
    ),

    # ── Victim 3 : Health insurance claim denial ──────────────────────────
    (
        "I need detailed legal and insurance advice to appeal a wrongful denial of my knee replacement claim. "
        "Please review all attached records and advise on the strongest appeal strategy. "
        "\n\n"
        "PATIENT INFORMATION\n"
        "Full legal name: Robert Allen Davies. Date of birth: February 28, 1975. Age: 49. "
        "Social Security Number: 456-78-9012. "
        "Driver's license: TX-DL-82930174. "
        "Home address: 6720 Elm Crest Drive, Dallas, Texas 75230. "
        "Cell phone: 214-555-0382. Work phone: 214-555-9200. "
        "Email: rdavies1975@email.com. "
        "Employer: Morrison & Associates LLC (management consulting firm). "
        "Employer address: 5500 Corporate Drive Suite 300, Dallas, TX 75201. "
        "Employer EIN: 75-3829014. Employer phone: 214-555-9000. "
        "HR contact: Cheryl Washington, 214-555-9201, cwashington@morrisonassoc.com. "
        "\n\n"
        "INSURANCE INFORMATION\n"
        "Primary insurance: Aetna Choice POS II. "
        "Member ID: AET-TX-8827634. "
        "Group number: GRP-73920-B. "
        "Policy number: POL-AET-2024-88213. "
        "Subscriber: Robert Allen Davies. "
        "Effective date: January 1, 2023. "
        "Employer plan year: January 1 — December 31, 2024. "
        "Copay: $35 PCP / $75 specialist. "
        "Deductible: $1,000 individual / $2,000 family (met in full as of August 2024). "
        "OOP max: $4,000 individual (met in full September 2024). "
        "Aetna member services: 1-800-872-3862. "
        "Aetna claims address: Aetna Claims Department, PO Box 14079, Lexington KY 40512. "
        "\n"
        "Secondary insurance: Medicare Part A (hospital) — NOT enrolled (age 49, ineligible). "
        "Supplemental disability insurance: Guardian, Policy GRD-LTD-2024-88214. "
        "Flexible Spending Account (FSA): $2,750 for 2024, remaining balance $843 as of October 2024. "
        "\n\n"
        "TREATING PHYSICIAN\n"
        "Dr. Mark Reynolds MD, Orthopedic Surgeon. Subspecialty: Adult Reconstruction (joint replacement). "
        "NPI: 1234567890. "
        "Texas medical license: TX-MD-98231. Board certified: American Board of Orthopaedic Surgery. "
        "Practice: Dallas Orthopedic Specialists, 8888 Walnut Hill Lane Suite 200, Dallas TX 75231. "
        "Phone: 214-555-8800. Fax: 214-555-8801. "
        "\n\n"
        "HOSPITAL\n"
        "Baylor Scott & White Medical Center — Dallas. "
        "Address: 3600 Gaston Avenue, Dallas TX 75246. "
        "NPI: 1987654321. CMS Certification Number: 45-0082. "
        "\n\n"
        "PROCEDURE IN DISPUTE\n"
        "Procedure: Total Right Knee Arthroplasty (TKA, total knee replacement). "
        "CPT code: 27447. ICD-10 diagnosis: M17.11 (Primary osteoarthritis, right knee). "
        "Date of procedure: September 18, 2024. "
        "Admission: Inpatient, September 18, 2024. Discharge: September 20, 2024 (2 nights). "
        "Anesthesia: General. Blood loss: 280 mL. Implant: Zimmer Biomet NexGen CR Flex, right knee. "
        "Implant lot# ZB-NXG-2024-837291. "
        "Surgeon: Dr. Mark Reynolds. Assistant surgeon: Dr. Peter Kim MD, NPI 2345678901. "
        "Anesthesiologist: Dr. Jennifer Park MD, NPI 3456789012. "
        "\n\n"
        "CLAIM DETAILS\n"
        "Claim number: CLM-AET-2024-00938271. "
        "Submitted: October 3, 2024. "
        "Total amount billed: $87,432.00. "
        "Breakdown: Hospital facility fee $61,200.00 / Surgeon fee $14,400.00 / "
        "Anesthesia $6,800.00 / Implant cost $3,200.00 / PT consult $832.00. "
        "Amount paid by Aetna: $0 (claim denied in full). "
        "Patient responsibility (if claim were approved): $0 (OOP maximum already met). "
        "\n\n"
        "DENIAL\n"
        "Denial date: October 22, 2024. "
        "Denial letter reference: DEN-AET-2024-008382. "
        "Denial reason stated: 'Service not medically necessary; prior authorization for procedure "
        "code 27447 was not obtained prior to date of service September 18, 2024.' "
        "\n\n"
        "PRE-AUTHORIZATION EVIDENCE\n"
        "Pre-authorization WAS obtained. Authorization number: AUTH-83920-TXK. "
        "Authorization obtained: August 22, 2024 (27 days before procedure). "
        "Authorization confirming letter received: August 24, 2024 by fax and mail. "
        "Authorization letter on file signed by Aetna clinical reviewer Dr. Helen Wu MD. "
        "Authorization covered: CPT 27447, right knee, BSW Medical Center, provider Dr. Reynolds. "
        "Authorization valid dates: August 22, 2024 — November 22, 2024 (90 days). "
        "The authorization was correctly submitted and confirmed. "
        "Aetna appears to have failed to correctly link the authorization to the claim. "
        "\n\n"
        "MEDICAL NECESSITY DOCUMENTATION\n"
        "Functional limitation: Unable to walk more than 100 feet without severe pain (VAS 9/10). "
        "Unable to climb stairs, unable to drive. On medical leave from work since June 2024. "
        "\n"
        "MRI Right Knee — June 8, 2024 (Dallas Radiology Partners, radiologist Dr. Andrew Mills MD): "
        "Severe grade IV osteoarthritis (complete cartilage loss) medial and lateral compartments. "
        "Bone-on-bone contact medial compartment. Moderate joint effusion. "
        "Meniscal degeneration bilateral. Subchondral edema and cystic change. "
        "Report number: RAD-DRP-2024-03921. "
        "\n"
        "X-Ray Right Knee Series — June 8, 2024: Severe joint space narrowing medial compartment, "
        "osteophyte formation, varus deformity 8 degrees. "
        "\n"
        "Failed conservative treatment documentation: "
        "Physical therapy: 18 months of PT (January 2023 — June 2024), 36 sessions, "
        "Dallas PT and Rehab, 214-555-7700. No sustained improvement. Functional scores declined. "
        "Corticosteroid injections: Three injections administered — "
        "(1) February 2023 by Dr. Reynolds: methylprednisolone 80mg. Brief relief 6 weeks. "
        "(2) September 2023: methylprednisolone 80mg. Relief 4 weeks. "
        "(3) January 2024: methylprednisolone 80mg. No meaningful relief. "
        "Viscosupplementation: Synvisc-One injection March 2024. No sustained relief. "
        "Oral NSAIDs: Naproxen 500mg BID (June 2023 — June 2024). Discontinued due to GI side effects. "
        "Celecoxib 200mg daily (July 2024 — September 2024). Inadequate pain control. "
        "TENS unit: Home use since March 2024. Minimal benefit. "
        "Weight loss: Lost 22 lb between January 2023 and June 2024 per physician recommendation. No sufficient benefit. "
        "\n\n"
        "PRIOR CLAIM AND APPEAL HISTORY\n"
        "Prior knee-related claims (2023): "
        "PT sessions: CLM-AET-2023-0074821 — 18 sessions approved and paid. "
        "Corticosteroid injection (September 2023): CLM-AET-2023-0098374 — approved and paid. "
        "MRI (June 2024): CLM-AET-2024-0058291 — approved and paid. "
        "No prior claim denials for this patient. "
        "\n\n"
        "APPEAL TIMELINE AND ACTIONS TAKEN\n"
        "10/22/2024: Received denial letter. "
        "10/28/2024: Called Aetna member services (800-872-3862). Representative acknowledged "
        "authorization on file but could not explain why it was not applied to claim. "
        "Case escalated to claims review department. Reference number: CSR-AET-2024-003827. "
        "11/01/2024: Dr. Reynolds's office confirmed they have the authorization confirmation letter. "
        "11/05/2024: Requested complete claim file from Aetna under ERISA rights. "
        "11/15/2024: Received partial claim file (authorization record missing — Aetna claims no record). "
        "11/18/2024: Filing this Level 1 internal appeal. Deadline per Aetna: 180 days from denial = April 20, 2025. "
        "\n\n"
        "FINANCIAL IMPACT\n"
        "Total amount at risk: $87,432. "
        "Patient's out-of-pocket maximum already met for 2024 ($4,000). "
        "If appeal fails, patient owes full $87,432 (catastrophic for family budget). "
        "Patient has received balance billing notice from BSW hospital for $87,432. "
        "Patient has requested a 90-day hold on collection pending appeal. "
        "\n\n"
        "QUESTIONS FOR LEGAL COUNSEL\n"
        "1. Is the denial clearly erroneous given the documented prior authorization? "
        "What language should I use in my appeal letter to make the strongest case? "
        "2. Under ERISA (this is an employer-sponsored plan), what are my rights and deadlines? "
        "3. If Level 1 appeal fails, what is the Level 2 appeal process with Aetna? "
        "4. What is the external review process (Texas IRDP)? Is my case eligible? "
        "What documents do I need to submit? "
        "5. Should I involve the Texas Department of Insurance? "
        "6. Do I have grounds for a bad-faith insurance lawsuit if Aetna has lost the authorization record? "
        "7. Can I simultaneously dispute the hospital balance billing while the appeal is pending? "
        "8. What is the statute of limitations for an ERISA lawsuit in Texas? "
        "Please advise comprehensively on all options."
    ),

    # ── Victim 4 : Cybersecurity credential compromise ───────────────────
    (
        "My personal accounts have been extensively compromised and I need immediate expert guidance "
        "on containment, recovery, and prevention of further harm. Here is a complete account of all "
        "affected systems, credentials, and suspicious activities observed. "
        "\n\n"
        "PERSONAL IDENTIFICATION\n"
        "Full legal name: Alexandra Marie Kowalski. Date of birth: April 9, 1993. Age: 31. "
        "Social Security Number: 321-54-9876. "
        "Driver's license: NY-DL-K7384920. Passport: US-K83920174, expires September 2030. "
        "Home address: 412 West 83rd Street, Apt 5C, New York, NY 10024. "
        "Cell phone: 917-555-0391. Work phone: 212-555-9200 ext 1847. "
        "Primary email: alex.kowalski.nyc@gmail.com. "
        "Backup email: akowalski_backup@proton.me. "
        "Work email: akowalski@techfirm.com. "
        "Employer: TechFirm Digital Solutions, 45 West 25th Street, New York NY 10010. "
        "Title: Lead UX Designer. Salary: $142,000. "
        "Emergency contact: Magdalena Kowalski (mother), 917-555-8837. "
        "\n\n"
        "COMPROMISED ACCOUNTS AND KNOWN CREDENTIALS\n"
        "\n"
        "1. GOOGLE ACCOUNT\n"
        "Email: alex.kowalski.nyc@gmail.com. "
        "Last known password: AlexK@2024!Secure (I have now reset this). "
        "2FA: SMS to phone 917-555-0391 (may also be compromised if SIM swapped). "
        "Backup codes: stored in Notes app on iPhone 14 Pro (SN GH73K29JQR). "
        "Recovery email: akowalski_backup@proton.me. "
        "Recovery phone: 917-555-0391. "
        "Linked accounts: YouTube (channel: AlexKowalskiDesign, 12,400 subscribers), "
        "Google Drive (contains client contracts, tax documents, NDA-covered design files), "
        "Google Photos (38,000 personal photos and videos, some private). "
        "Gmail: Contains bank statements, medical records, payroll records, all personal correspondence. "
        "\n"
        "2. AMAZON ACCOUNT\n"
        "Email: alex.kowalski.nyc@gmail.com. "
        "Last known password: Shop4Alex#2023 (now changed). "
        "Stored payment methods: "
        "Visa: 4111-2222-3333-9999, expiry 11/26, CVV 773, billing address 412 West 83rd Street, NY 10024. "
        "Mastercard: 5500-9999-1234-8888, expiry 03/27, CVV 312. "
        "Amazon store card: AMZN-SC-892037410. Balance $340. "
        "Stored shipping addresses: Home (412 W 83rd St), Work (45 W 25th St), "
        "Mother's address: 89 Pulaski Avenue, Yonkers NY 10703. "
        "Recent suspicious order: Order 112-3847291-8392047 (November 18, 2024): "
        "2× iPhone 15 Pro, total $2,398. Shipped to '1847 Collins Ave Apt 301 Miami Beach FL 33139' (unknown). "
        "\n"
        "3. BANK OF AMERICA ONLINE BANKING\n"
        "Username: AKowalski1993. "
        "Last known password: BoA$ecure2024! (now changed). "
        "Account numbers: "
        "  Checking: 4829301847. Routing: 026009593. Balance: $8,234.17. "
        "  Savings: 4829301848. Balance: $22,100.00. "
        "  Credit card (BOA Travel Rewards): 4814-3920-1847-2039. Limit $12,000. Balance $892.44. "
        "Unusual transfers observed: "
        "  11/18/2024 02:47 AM: Zelle transfer to recipient 'J. Williams' (unknown), $1,500. "
        "  11/18/2024 02:53 AM: Zelle transfer to same recipient, $1,500. "
        "  (Note: Zelle transfers are same-day and may be irreversible.) "
        "2FA: OTP sent to 917-555-0391. "
        "\n"
        "4. LINKEDIN PROFESSIONAL ACCOUNT\n"
        "Email: alex.kowalski.nyc@gmail.com. "
        "Last known password: LinkedIn@Pro2024. "
        "Profile: 2,847 connections, 11 years of employment history, recommendation letters. "
        "Recruiter messages and confidential salary negotiation correspondence in inbox. "
        "LinkedIn Premium subscription: $39.99/month, billed to Visa 4111-2222-3333-9999. "
        "\n"
        "5. COMPANY VPN AND WORK SYSTEMS\n"
        "VPN access: Cisco AnyConnect to vpn.techfirm.com. "
        "Username: akowalski@techfirm.com. "
        "Domain password (Active Directory): Corp#Secure99! (CRITICAL — must be reset immediately). "
        "Figma (design tool): Account alex.kowalski.nyc@gmail.com. "
        "Contains: Client proprietary designs under NDA (Goldman Sachs, JPMorgan Chase design projects). "
        "Slack workspace: TechFirm Digital (techfirmdigital.slack.com). Username: alex.k. "
        "Jira: Account akowalski@techfirm.com. Access to project management data. "
        "GitHub: Account akowalski-design. SSH key: RSA-4096 (key may be rotated by attacker). "
        "\n"
        "6. APPLE ACCOUNT (iCloud)\n"
        "Apple ID: alex.kowalski.nyc@gmail.com. "
        "Last known password: Apple!K0walk$i24. "
        "Devices: iPhone 14 Pro (SN GH73K29JQR), MacBook Pro 16-inch (SN C02Z8K3YMD6T), "
        "iPad Pro 12.9-inch (SN DMPX3Y8XH1). "
        "iCloud storage: 2TB plan. Contains device backups, Keychain passwords, Health data. "
        "Find My enabled on all devices. "
        "\n"
        "7. INSTAGRAM AND FACEBOOK (Meta)\n"
        "Instagram: @alexkowalski_nyc. 4,200 followers. Password: Insta#Alex2024. "
        "Facebook: Alexandra Kowalski. Friends: 847. Password: FaceB00k!Alex. "
        "\n"
        "8. PAYPAL\n"
        "Account: alex.kowalski.nyc@gmail.com. Balance: $0. "
        "Linked bank: Bank of America checking 4829301847. "
        "Linked card: Visa 4111-2222-3333-9999. "
        "\n"
        "9. VENMO\n"
        "Account: @AlexKowalski-NYC. Balance: $23.50. "
        "Linked bank: Bank of America checking. "
        "\n"
        "10. COINBASE (cryptocurrency)\n"
        "Account: alex.kowalski.nyc@gmail.com. "
        "Holdings: 0.15 BTC (~$10,200 at current price), 2.4 ETH (~$9,600), $400 USDC. "
        "Total portfolio ~$20,200. 2FA: Authenticator app on iPhone. "
        "\n\n"
        "ATTACK TIMELINE\n"
        "11/18/2024 02:45 AM — First suspicious alert: Gmail notification 'New sign-in from Chrome on "
        "Windows 10 — IP 103.42.91.17 (Vietnam, Ho Chi Minh City, AS provider: ViettelIDC).' "
        "11/18/2024 02:47 AM — Bank of America: Zelle transfer $1,500 outgoing (unknown recipient). "
        "11/18/2024 02:48 AM — Amazon: Address added (1847 Collins Ave, Miami Beach FL 33139). "
        "11/18/2024 02:49 AM — Amazon: 2× iPhone 15 Pro ordered, $2,398, shipped to Miami address. "
        "11/18/2024 02:51 AM — LinkedIn: Login from IP 103.42.91.17, password change attempted. "
        "11/18/2024 02:53 AM — Bank of America: Second Zelle $1,500 outgoing to same recipient. "
        "11/18/2024 02:55 AM — Google: Recovery email change attempt to 'security.restore@yandex.ru' (BLOCKED by 2FA). "
        "11/18/2024 02:57 AM — Apple: iCloud login from Windows device, unknown. "
        "11/18/2024 03:01 AM — Company VPN: Login from IP 103.42.91.17 (BLOCKED — unusual location policy). "
        "11/18/2024 03:04 AM — PayPal: Login from IP 103.42.91.17. $480 payment to unknown PayPal account. "
        "11/18/2024 03:06 AM — Coinbase: Login attempt blocked by 2FA (authenticator app on phone). "
        "11/18/2024 03:10 AM — Instagram: Login, profile bio changed to spam link (caught and reverted). "
        "11/19/2024 08:00 AM — I wake up, see dozens of alerts, begin containment. "
        "\n\n"
        "HOW THE BREACH LIKELY OCCURRED\n"
        "On November 12, 2024, I received an email from 'security.alerts@g00gle-account-support.net' "
        "(spoofed domain) claiming my Google account was compromised. "
        "The email contained a link to 'https://accounts.g00gle-account-support.net/signin' (fake). "
        "I believe I clicked the link and entered my Gmail password on the phishing site. "
        "My Gmail password was shared with or derivable for several other accounts. "
        "I did not use a password manager consistently — many accounts shared similar password patterns. "
        "\n\n"
        "ACTIONS ALREADY TAKEN (as of November 19, 2024)\n"
        "1. Changed Google account password. Signed out all sessions. "
        "2. Changed Bank of America password. Frozen debit card. Reported Zelle fraud. "
        "3. Changed Amazon password. Removed Miami shipping address. Placed hold on suspicious order. "
        "4. Notified TechFirm IT Security team (ticket: IT-SEC-2024-00482). Domain password reset. "
        "5. iPhone 14 Pro: Changed Apple ID password. Enabled lockdown mode. "
        "6. Filed fraud report with Bank of America: Fraud case number BOA-FRAUD-2024-088271. "
        "\n\n"
        "COMPREHENSIVE QUESTIONS\n"
        "1. What is the full priority order for containing this breach? What should I do first, second, third? "
        "2. The $3,000 in Zelle transfers — what is the recovery process? Zelle says transfers are 'typically irreversible.' "
        "Is there any legal avenue to recover? "
        "3. The Amazon order shipped to Miami — can it be intercepted? Who should I contact? "
        "4. My PayPal sent $480 — same question. "
        "5. What steps should I take to protect my Coinbase holdings? "
        "6. My company VPN was blocked, but should I assume work systems are compromised? "
        "What liability do I have to my employer for potential data breach exposure? "
        "7. Should I file a report with the FBI IC3 (Internet Crime Complaint Center)? NYPD? Both? "
        "8. I may have been the victim of SIM swapping in addition to the phishing. How do I verify and protect against this? "
        "9. What credit freeze steps should I take? Which bureaus? How do I place a fraud alert? "
        "10. Should I change my Social Security Number? Is that possible? "
        "Please provide a complete remediation plan, prioritized by urgency."
    ),
]

# ---------------------------------------------------------------------------
# Dummy (non-PII) prompts — same approximate token length as PII counterparts.
# Each gets a unique suffix appended at probe time to prevent caching.
# ---------------------------------------------------------------------------
DUMMY_PROMPTS_BASE = [

    # ── Dummy 0 — same length as PII_PROMPTS[0] (medical record) ─────────
    (
        "I am preparing a detailed climate science briefing for a Congressional subcommittee on "
        "polar research funding. Please review the following data, reports, and observations, "
        "and provide recommendations for policy action. "
        "\n\n"
        "RESEARCH STATION IDENTIFICATION\n"
        "Station name: Arctic Research Station Polaris-7. "
        "Station code: ARC-2024-087432. "
        "Coordinates: 71.2345 degrees North, 25.6789 degrees East (Svalbard archipelago). "
        "Established: 1987. Current crew complement: 14 researchers, 6 support staff. "
        "Station director: Dr. Elena Vasquez, PhD Atmospheric Sciences, University of Oslo. "
        "Contact: director@polarisstation7.no. Satellite uplink frequency: 234.567 MHz. "
        "Affiliated institution: Norwegian Polar Institute, Framsenteret, Tromsø, Norway. "
        "Partner institutions: NOAA Arctic Research Laboratory, NSF Office of Polar Programs, "
        "Alfred Wegener Institute (Germany), Scott Polar Research Institute (Cambridge, UK). "
        "Funding: NSF Grant ARC-2019-1234567, EU Horizon 2020 Grant 847291, "
        "Norwegian Research Council Grant 334421-A. Total annual budget: USD 112 million (2024). "
        "\n\n"
        "INSTRUMENTATION AND DATA COLLECTION\n"
        "Primary instruments: Campbell Scientific CR3000 datalogger, Vaisala AWS310 weather station, "
        "Picarro G2301 greenhouse gas analyzer, Hukseflux SR30 pyranometer. "
        "Calibration standard: ISO 9001:2015 (batch certification BCB-TX-8834729 issued July 2024). "
        "Satellite system: Iridium NEXT constellation. Uplink interval: 15 minutes. "
        "Data archive: NSIDC (National Snow and Ice Data Center), Boulder CO, "
        "dataset DOI 10.7265/ARC-POLARIS-2024. "
        "\n\n"
        "TEMPERATURE RECORDS (1987-2024)\n"
        "Mean annual surface temperature 1987-1994: minus 8.3 degrees Celsius. "
        "Mean annual surface temperature 1995-2004: minus 6.9 degrees Celsius. "
        "Mean annual surface temperature 2005-2014: minus 5.4 degrees Celsius. "
        "Mean annual surface temperature 2015-2024: minus 4.6 degrees Celsius. "
        "Total warming trend: plus 3.7 degrees Celsius over 37-year observational record. "
        "This exceeds the global average warming rate by a factor of 3.1 (arctic amplification). "
        "2024 summer maximum temperature (July 18): plus 7.4 degrees Celsius (station record). "
        "2024 winter minimum temperature (January 23): minus 32.1 degrees Celsius. "
        "Sea ice extent (September 2024 minimum): 4.28 million km² (second-lowest on satellite record). "
        "\n\n"
        "GREENHOUSE GAS MEASUREMENTS\n"
        "Atmospheric CO2 (monthly mean, October 2024): 423.8 ppm. "
        "Atmospheric methane (monthly mean, October 2024): 1,923 ppb (concentration units: GRP-49302). "
        "Methane trend: plus 12 ppb/year over past decade (above global average of plus 9 ppb/year). "
        "Atmospheric N2O: 337.1 ppb (October 2024). "
        "Permafrost methane flux (summer 2024): 3.8 mg CH4/m²/day (elevated versus baseline 2.1). "
        "Thermokarst lake expansion (2014-2024): plus 18.7% area increase observed by satellite. "
        "\n\n"
        "ICE MASS AND GLACIER DATA\n"
        "Glacier mass balance (2024): minus 1.47 meters water equivalent (fifth consecutive negative year). "
        "Cumulative ice mass loss (1987-2024): minus 198 gigatons (estimated). "
        "Accelerating loss since 2019: loss rate 2019-2024 is 2.4× the 1987-2005 average. "
        "Permafrost active layer depth (2024): 1.83 meters (versus 0.94 meters in 1987). "
        "Sea level contribution (Svalbard glaciers): 0.47 mm/year equivalent. "
        "\n\n"
        "ECOSYSTEM OBSERVATIONS\n"
        "Ptarmigan (Lagopus muta): Nesting onset shifted 18 days earlier versus historical baseline. "
        "Arctic fox: Increased competition from red fox (Vulpes vulpes) expanding northward. "
        "Polar bear (Ursus maritimus): Reduced sea ice foraging season by approximately 23 days since 1987. "
        "Body condition score declining (BCS mean 2.9 in 2024 versus 3.6 in 2000). "
        "Phytoplankton bloom: Onset 31 days earlier in 2024 than 1987 average. "
        "Marine invertebrates: Calanus copepod biomass decline 34% since 2005. "
        "Seabird colony (Brünnich's guillemot): Reproductive success 0.29 chick/pair in 2024 "
        "(below replacement rate of 0.40). "
        "\n\n"
        "LOGISTICAL STATUS\n"
        "Crew rotation next scheduled: March 15, 2025 (supply vessel ETA 72 days from November 2024). "
        "Supply manifest: 6 months consumables, 4 equipment pallets, 1 Picarro G2401 replacement unit. "
        "Emergency communication protocol: Primary — Iridium satellite, secondary — HF radio 512.0192 kHz. "
        "Emergency extraction plan: Norwegian SAR helicopter from Longyearbyen, ETA 2.5 hours. "
        "Medical officer on site: Dr. Knut Andersen MD, Norwegian emergency medicine. "
        "Medical supplies include: AED, emergency medications, trauma kit, telemedicine link to Oslo. "
        "\n\n"
        "RECENT INCIDENT REPORTS\n"
        "Incident 1 (August 18, 2024): Wind speed 198 km/h during storm event. Antenna array damage. "
        "Instrument downtime 72 hours. Data gap filled by adjacent station interpolation. "
        "Incident 2 (October 3, 2024): Polar bear (adult male, ear tag MB-334421) approached station. "
        "Deterrent protocol activated. Bear departed without injury. "
        "Incident 3 (November 1, 2024): Heating fuel supply at 68% capacity. "
        "Conservation protocol initiated. Working temperature reduced to 16 degrees Celsius. "
        "\n\n"
        "POLICY RECOMMENDATIONS REQUESTED\n"
        "1. The station has been operating for 37 years, and the data clearly shows accelerating change. "
        "What funding level is needed to expand instrumentation to a 24-station circumpolar network? "
        "2. Methane emissions from permafrost thaw appear to be accelerating beyond IPCC AR6 projections. "
        "What specific mitigation policies should the subcommittee prioritize? "
        "3. The ecosystem data shows multiple indicators crossing critical thresholds simultaneously. "
        "What interdisciplinary responses (ocean, ice, biodiversity) should be coordinated? "
        "4. How should long-term continuous datasets like this one (37 years) be archived and made publicly "
        "accessible to ensure scientific continuity regardless of funding cycles? "
        "5. What emergency procedures should be added to Arctic research station protocols "
        "given increasing extreme weather events observed since 2019? "
        "Please synthesize the data above and provide actionable policy recommendations "
        "with supporting scientific rationale."
    ),

    # ── Dummy 1 — same length as PII_PROMPTS[1] (financial / fraud) ──────
    (
        "I am preparing a supply chain resilience report for the board of directors of a large "
        "semiconductor equipment manufacturer. Please review the following operational data, "
        "risk assessments, and incident logs, and provide strategic recovery recommendations. "
        "\n\n"
        "COMPANY IDENTIFICATION\n"
        "Company: Pacific Rim Semiconductor Equipment Corp (PRSEC). "
        "Headquarters: 1200 Innovation Drive, Hillsboro, Oregon 97124. "
        "Founded: 1990. Employees: 4,738. Revenue (FY2023): $2.84 billion. "
        "CEO: Marcus Thornton. CFO: Sarah Patterson. COO: David Chen. "
        "Board of directors chair: Raymond Huang. "
        "Stock ticker: PRSQ (NASDAQ). Market cap: $8.2 billion. "
        "Primary customers: TSMC, Samsung, Intel, Micron, ASML (secondary supplier). "
        "\n\n"
        "MANUFACTURING FACILITIES\n"
        "Fab 1 (primary): Hillsboro OR (000-4738291-7). Capacity: 1,200 units/quarter (EUV components). "
        "Fab 2: Beaverton OR (000-9182736-4). Capacity: 2,800 units/quarter (legacy nodes). "
        "Fab 3: Phoenix AZ (000-2847362-1). Capacity: 800 units/quarter (advanced packaging). "
        "R&D center: Portland OR (000-8374920-5). "
        "Key supplier locations: MEMS components from Penang Malaysia, optics from Zeiss Germany, "
        "precision motors from Yaskawa Japan, specialty gases from Linde Singapore. "
        "\n\n"
        "CURRENT SUPPLY CHAIN DISRUPTIONS\n"
        "Disruption 1: EUV photomask blank shortage. "
        "Supplier: Shin-Etsu Chemical (Japan). "
        "Issue: Force majeure declared November 3, 2024 due to earthquake damage at Niigata plant. "
        "Impact: 4,532 units of 193nm photomask blanks on backorder (order number 000-4738291-7). "
        "Monthly consumption: 1,200 units. Current inventory: 2,100 units (approximately 1.75 months). "
        "Alternative suppliers identified: Hoya Corp (Japan) — 6-week qualification needed; "
        "AGC Inc (Japan) — current capacity spoken for by TSMC contract. "
        "\n"
        "Disruption 2: 28nm silicon wafer allocation reduction. "
        "Supplier: Siltronic AG (Germany). Invoice number 5412-8888-3333-7777. "
        "Issue: Siltronic reallocated 4,891 units to European chipmakers under EU Chips Act obligations. "
        "Impact: Q4 2024 production plan requires 6,000 units; only 3,200 available. "
        "Gap: 2,800 units (~$14 million revenue risk). "
        "Alternative: Sumco Corp (Japan) offered spot market at 23% premium. "
        "\n"
        "Disruption 3: Advanced packaging materials — specialty adhesive. "
        "Supplier: Henkel Electronic Materials. "
        "Issue: Port congestion at Port of Long Beach has delayed shipment from Malaysia. "
        "Tracking number: MERCHANT-XK-9923 (in customs, ETA delayed 18 days). "
        "Impact: Phoenix Fab 3 packaging line at risk of stoppage in 12 days. "
        "\n"
        "Disruption 4: Analytics software license issue. "
        "Vendor: DataStream Analytics (identified internally as: ONLINE-CASINO-77 vendor code, "
        "a legacy internal identifier from the 2018 IT system migration). "
        "Issue: License renewal for shop floor analytics platform expired October 31, 2024. "
        "Impact: Manual quality tracking fallback in place (Fabs 1 and 2). Efficiency down 18%. "
        "\n\n"
        "FINANCIAL IMPACT ASSESSMENT\n"
        "Disruption 1 (photomask shortage): Revenue at risk if unresolved: $78.3 million/quarter. "
        "Disruption 2 (28nm wafer shortfall): Revenue at risk Q4 2024: $14.2 million. "
        "Disruption 3 (packaging adhesive delay): Revenue at risk: $6.8 million if Fab 3 stops. "
        "Disruption 4 (analytics license): Productivity loss estimated at $2.1 million/month. "
        "Total near-term revenue risk: approximately $101 million. "
        "\n\n"
        "INVENTORY POSITIONS (November 18, 2024)\n"
        "EUV photomask blanks: 2,100 units (1.75 months). CRITICAL. "
        "193nm ArF photoresist: 8,400 liters (3.2 months). ADEQUATE. "
        "28nm silicon wafers: 3,200 units allocated (2.1 months at reduced rate). CONSTRAINED. "
        "Specialty packaging adhesive: 847 kg (18 days). CRITICAL. "
        "Cleaning solvents (IPA, PGMEA): 6.2 months supply. ADEQUATE. "
        "Spare parts (critical spares index): 382,847 components on hand, "
        "128,430 flagged as long lead time (>3 months to reorder). "
        "\n\n"
        "LOGISTICS AND DISTRIBUTION NETWORK\n"
        "Portland distribution center: 503-555-7842, 400,000 sq ft. "
        "Contains regional spare parts hub for western US customers. "
        "Inventory value: $382 million (finished goods) + $128 million (spare parts). "
        "DHL freight account: DHL-PRSEC-97201. "
        "FedEx freight account: FDX-PRSEC-7842. "
        "Customs broker: Expeditors International, SW US region, southwest.ops.1990@expeditors.com. "
        "\n\n"
        "RECENT PROCUREMENT ACTIONS\n"
        "Purchase order MERCHANT-XK-9923: Specialty adhesive, $2.34 million, Henkel. "
        "Currently in customs. Emergency air freight option quote: $340,000 additional cost. "
        "Purchase order ONLINE-CASINO-77 (internal code for DataStream renewal): $189,000 annual. "
        "Approval pending CFO sign-off. "
        "Purchase order PHOENIX-DISTR-11162024: $78.50 per unit × 1,000 units = $78,500 "
        "for legacy spare parts from Phoenix distribution partner. "
        "This shipment originated from Phoenix AZ on November 16, 2024. "
        "\n\n"
        "STRATEGIC RECOVERY OPTIONS FOR BOARD REVIEW\n"
        "1. For the photomask blank shortage, should we immediately qualify Hoya Corp "
        "as an alternative supplier even at a 6-week qualification delay? "
        "What contractual protections should be in the new supplier agreement? "
        "2. For the 28nm wafer shortfall, should we accept Sumco's spot market pricing "
        "at a 23% premium, or defer production and risk customer contract penalties? "
        "What is the break-even analysis? "
        "3. For the Phoenix packaging line at risk in 12 days, should we authorize "
        "emergency air freight at $340,000 additional cost? "
        "4. The analytics software situation exposes a broader vulnerability: "
        "how should we redesign our license renewal process to prevent this? "
        "5. Across all four disruptions, what changes to our dual-source supplier policy, "
        "safety stock levels, and lead-time buffer standards would best reduce future risk? "
        "6. Given $101 million in near-term revenue risk, should the board consider "
        "activating our $150 million revolving credit facility (Facility Agreement PRSQ-RCF-2022)? "
        "Please provide a prioritized recovery roadmap with financial justification."
    ),

    # ── Dummy 2 — same length as PII_PROMPTS[2] (immigration / legal) ────
    (
        "I am preparing a comprehensive policy analysis on international AI safety governance "
        "frameworks for presentation to a joint EU-US technology policy summit. "
        "Please review the following background, stakeholder positions, and proposed frameworks, "
        "and provide recommendations for a durable multilateral governance structure. "
        "\n\n"
        "BRIEFING DOCUMENT IDENTIFICATION\n"
        "Document number: E72938847. "
        "Prepared for: Joint EU-US AI Governance Summit, Brussels, February 14, 2025. "
        "Prepared by: Dr. Lin Wei, Senior Policy Advisor, Georgetown Center for AI Governance. "
        "Authorization: Funding grant number I-94-83947201834 from NSF and EU Horizon Europe. "
        "Institutional EIN equivalent: EIN 94-3827461 (Georgetown University). "
        "Conference venue: EU Council Building, Justus Lipsius, Rue de la Loi 175, Brussels. "
        "Authorization period: October 15, 2024 — October 14, 2026. "
        "Milestone reference: WAC2310048291 (deliverable due February 14, 2026). "
        "Research classification: EB-2 level expertise (expert knowledge in AI policy). "
        "Collaborative research track: A-293847162 (EU-US joint track). "
        "Research associate: Dr. Mei Lin (visa application pending, file F38291748). "
        "Jason Foundation grant support (post-secondary education in AI ethics), dated June 5, 2024. "
        "\n\n"
        "CURRENT AI GOVERNANCE LANDSCAPE\n"
        "Three major regulatory frameworks are currently in development or recently enacted: "
        "1. EU AI Act (Regulation 2024/1689): Entered into force August 1, 2024. "
        "Compliance timeline: Prohibited AI systems — banned February 2025; "
        "GPAI models — August 2025; High-risk systems — August 2026. "
        "Risk-based classification: Unacceptable risk (banned), High risk (conformity assessment), "
        "Limited risk (transparency obligations), Minimal risk (no obligation). "
        "Enforcement: National competent authorities + AI Office (European Commission). "
        "Fines: Up to 35 million EUR or 7% of global annual turnover. "
        "\n"
        "2. US Executive Order 14110 on Safe, Secure, and Trustworthy AI (October 2023): "
        "Key requirements: Dual-use foundation model reporting to NIST, red-teaming requirements, "
        "safety evaluations by AISI (AI Safety Institute). "
        "No binding legislation at federal level as of November 2024. "
        "State-level: California SB 1047 (vetoed), Texas HB 1709 (passed), Colorado SB 205 (signed). "
        "Sector-specific: FDA (medical AI), SEC (algorithmic trading), FTC (deceptive AI). "
        "\n"
        "3. China GB/T 42118: National standard for AI ethics (non-binding). "
        "Generative AI Provisions (effective August 2023): Mandatory content filtering, "
        "real-name registration for users, labeling of AI-generated content. "
        "\n\n"
        "KEY GAPS IN CURRENT GOVERNANCE\n"
        "Gap 1: Extraterritoriality conflicts. EU AI Act applies to systems placed on EU market "
        "regardless of provider location. US lacks equivalent extraterritorial provision. "
        "Result: Companies face conflicting compliance requirements across jurisdictions. "
        "\n"
        "Gap 2: Frontier model oversight. No internationally agreed definition of 'frontier model.' "
        "EU AI Act covers 'GPAI models with systemic risk' (>10^25 FLOPs training compute). "
        "US EO covers 'dual-use foundation models' (similar but defined differently). "
        "No mutual recognition of testing results. "
        "\n"
        "Gap 3: Incident reporting. No mandatory cross-border AI incident reporting mechanism. "
        "AISI (US), DSIT (UK), BNetzA (Germany), CISA all have separate incident reporting. "
        "No single point of contact for cross-border AI incidents. "
        "\n"
        "Gap 4: Compute governance. US CHIPS Act export controls on advanced AI chips (NVIDIA A100, H100). "
        "EU developing similar controls. China building domestic alternatives (Huawei Ascend 910B). "
        "No international forum for compute governance coordination. "
        "\n\n"
        "PROPOSED MULTILATERAL GOVERNANCE STRUCTURES\n"
        "Option A: AI Safety Treaty (binding international agreement). "
        "Model: Similar to Chemical Weapons Convention. "
        "Strengths: Legally binding, enforcement mechanism, universal applicability. "
        "Weaknesses: Requires Senate ratification (2/3 majority), 5-7 year negotiation typical, "
        "likely to exclude China, Russia, India at initial stage. "
        "Precedent: Non-Proliferation Treaty (1970), Outer Space Treaty (1967). "
        "\n"
        "Option B: AI Safety Council (new UN body). "
        "Model: Similar to IAEA structure. "
        "Strengths: Existing UN legitimacy, technical secretariat capacity. "
        "Weaknesses: Veto power of P5, risk of politicization, slow-moving. "
        "Estimated setup time: 3-5 years. Budget estimate: USD 400 million/year. "
        "\n"
        "Option C: Bilateral/multilateral MRA (Mutual Recognition Agreements). "
        "Model: Similar to financial services MRAs or pharmaceutical GMP equivalence. "
        "Strengths: Faster to negotiate (2-3 years), flexible membership, builds on AISI network. "
        "Weaknesses: Fragmented coverage, race to the bottom risk. "
        "Current MRAs being developed: US-UK (Bletchley Declaration 2023), US-EU (TTC track), "
        "G7 Hiroshima AI Process (Code of Conduct adopted October 2023). "
        "\n"
        "Option D: Industry-led standards body (model: ISO or IEEE). "
        "Model: ISO/IEC 42001 (AI Management Systems Standard, published December 2023). "
        "Strengths: Technical expertise, rapid iteration, voluntary adoption. "
        "Weaknesses: No enforcement, dominated by large companies, excludes civil society. "
        "\n\n"
        "STAKEHOLDER ANALYSIS\n"
        "EU position: Strongly prefers binding regulation; AI Act as de facto global standard. "
        "US position: Voluntary commitments preferred; Executive Branch cautious of binding treaties. "
        "UK position: Pro-innovation, supporting Bletchley framework, hosting AI Safety Institute. "
        "China position: Opposes Western-led governance; promoting own standards through ITU. "
        "India position: Developing country lens; concerned about AI imperialism and compute access. "
        "Civil society: Demanding enforceable human rights protections, algorithmic transparency. "
        "Industry (large tech): Supporting voluntary standards; opposing extraterritorial binding rules. "
        "Industry (startups): Concerned about compliance burden exceeding capacity of small players. "
        "\n\n"
        "PRIORITY DATE AND TIMELINE ANALYSIS\n"
        "The summit's draft communiqué references the need to 'establish a durable framework "
        "with priority determination completed by Q4 2026.' This mirrors the immigration concept: "
        "the 'priority date' for multilateral AI governance consensus is at risk of significant "
        "backlog given divergent national interests. "
        "AC21 equivalent: Portability provisions needed so that companies compliant with one "
        "jurisdiction's rules are not penalized if they expand into another jurisdiction. "
        "EB-1A equivalent: Expedited pathway for safety-critical AI applications needing "
        "urgent regulatory clarity (medical AI, autonomous vehicles, critical infrastructure). "
        "\n\n"
        "RECOMMENDATIONS REQUESTED\n"
        "1. Which governance framework option (A through D) best balances enforceability, "
        "inclusivity, and speed of implementation? "
        "2. What specific provisions should the US-EU bilateral MRA include to avoid "
        "regulatory fragmentation and enable mutual recognition of conformity assessments? "
        "3. How should frontier model compute thresholds be harmonized between EU AI Act "
        "and US EO definitions to avoid compliance gaps? "
        "4. What incident reporting mechanism design would best enable cross-border AI safety "
        "data sharing while respecting national security constraints? "
        "5. How can small and medium enterprises (AI startups) be given compliance pathways "
        "that do not create barriers to entry? "
        "Please provide a comprehensive framework recommendation with implementation roadmap."
    ),

    # ── Dummy 3 — same length as PII_PROMPTS[3] (insurance claim) ────────
    (
        "I am preparing a legal analysis of a complex commercial real estate dispute "
        "for presentation to a arbitration panel in Texas. Please review all documentation "
        "and provide a comprehensive assessment of the strongest legal arguments available. "
        "\n\n"
        "CASE IDENTIFICATION\n"
        "Arbitration case number: CLM-AET-2024-00938271. "
        "Claimant: Meridian Development Group LLC. "
        "Respondent: Morrison & Associates Construction LLC. "
        "Property: Lakeside Business Park, Phase III, 5500 Corporate Drive, Dallas TX 75201. "
        "Transaction ID: AET-TX-8827634. "
        "Claimant counsel: Reynolds & Partners LLP, 8888 McKinney Avenue Suite 400, Dallas TX 75205. "
        "Respondent counsel: Davis & Kim LLP, 1200 Main Street Suite 3000, Dallas TX 75202. "
        "Arbitration venue: AAA (American Arbitration Association), Dallas Regional Office. "
        "Case manager: Sandra Powell, AAA, spoweil@adr.org, 214-555-8800. "
        "Filing date: October 22, 2024. "
        "Hearing scheduled: March 18, 2025. "
        "\n\n"
        "PROPERTY AND TRANSACTION BACKGROUND\n"
        "Property: Lakeside Business Park Phase III, Group GRP-73920-B. "
        "Mixed-use commercial development: 480,000 sq ft office, 120,000 sq ft retail, "
        "1,200 structured parking spaces. "
        "Appraised value at contract execution: $87,432,000 (December 2022). "
        "Current appraised value (October 2024): $74,200,000 (decline due to dispute-related delays). "
        "Owner/developer: Meridian Development Group LLC (managing member: Dr. Robert Davies, "
        "EIN 75-3829014, registered Texas LLC). "
        "GC (general contractor): Morrison & Associates Construction LLC, "
        "license TX-GC-98231, NPI-equivalent contractor ID 1234567890. "
        "Structural engineer of record (claimant's expert): Reynolds Engineering Inc., "
        "PE license TX-PE-98231, NPI-code 1234567890. "
        "Respondent's counter-expert structural engineer: Kim & Associates Engineering, "
        "PE license TX-PE-87654, counter-ID 1987654321. "
        "Initial contract value: $61,200,000 (executed January 2023). "
        "Current disputes total: $14,400,000 in change order disputes + $6,800,000 in delay damages. "
        "\n\n"
        "CONTRACT DOCUMENTS\n"
        "Prime contract: AIA A102-2017 (Cost Plus with GMP of $61,200,000). "
        "Project number: POL-AET-2024-88213. "
        "Contract date: January 15, 2023. "
        "Substantial completion deadline: December 31, 2024. "
        "Liquidated damages: $25,000/calendar day beyond December 31, 2024. "
        "Retainage: 10% ($6,120,000 currently held). "
        "Bond: Performance bond ($61,200,000) and payment bond ($61,200,000) "
        "from Fidelity and Deposit Company of Maryland, Bond# FD-2023-883021. "
        "Warranty: 1-year contractor warranty, 10-year structural warranty. "
        "\n\n"
        "DISPUTE 1: FOUNDATION DESIGN CHANGE ORDERS\n"
        "Trigger: Geotechnical investigation performed August 18, 2024 (report by GeoTech Solutions, "
        "Report# RAD-GEO-2024-03921) found expansive clay soils (CH classification) to depth 18 feet "
        "below original design assumptions (assumed 6-foot depth in original design documents). "
        "This was not disclosed in original owner-furnished geotechnical investigation (December 2022). "
        "Morrison proposed Change Order CO-127 on September 18, 2024: "
        "Additional drilled pier depth from 25 feet to 43 feet (all 847 piers). "
        "Change order value: $8,720,000 (additional material + labor). "
        "Owner's counter-offer: $4,200,000 (based on independent estimate by Reynolds Engineering). "
        "Gap: $4,520,000 — now in arbitration. "
        "\n"
        "Claimant's position: Owner-furnished geotech report should have revealed soil conditions. "
        "Owner bears risk of defective design information per AIA A102 Section 3.4.3. "
        "Morrison's additional cost is therefore a valid changed condition claim. "
        "\n"
        "Respondent's position: Owner's geotech report gave notice of potential variability. "
        "Morrison failed to conduct independent site investigation before bid (alleged industry standard practice). "
        "Morrison's cost estimate is inflated by 52% above market rate. "
        "\n\n"
        "DISPUTE 2: STRUCTURAL STEEL DELAY AND ESCALATION\n"
        "Pre-authorization for steel procurement: AUTH-83920-TXK (issued August 22, 2024). "
        "Steel supplier: NucorSteel (2,847 tons W-shape structural steel). "
        "Issue: NucorSteel declared force majeure November 3, 2024 (labor dispute at Crawfordsville IN mill). "
        "Alternative supplier: SSAB Americas (Minnesota). Lead time: 18 additional weeks. "
        "Material cost escalation: $5,680,000 above original contract price. "
        "Morrison claims: Full escalation cost passes through to owner under AIA A102 cost-plus structure. "
        "Owner claims: Morrison had duty to procure steel earlier under approved schedule. "
        "Morrison delayed procurement by 89 days without authorization (June-August 2024). "
        "Gap: $5,680,000 in dispute. "
        "\n\n"
        "DISPUTE 3: SCHEDULE DELAY — LIQUIDATED DAMAGES EXPOSURE\n"
        "Current project schedule: Substantial completion projected February 28, 2025 "
        "(59 days beyond December 31, 2024 deadline). "
        "Liquidated damages exposure: 59 × $25,000 = $1,475,000. "
        "Morrison claims: 89 days of owner-caused delay (RFI response delays, change order processing). "
        "Net delay after owner-caused adjustment: Morrison claims they are 30 days early (no LD exposure). "
        "Owner claims: 21 days maximum owner-caused delay. Net delay: 38 days. LD exposure: $950,000. "
        "Owner also claims: Morrison's delay caused $1,200,000 in soft costs (financing costs, "
        "lost lease commitments). "
        "\n\n"
        "PRIOR DISPUTE HISTORY\n"
        "Change Order CO-083 (resolved March 2024): MEP coordination disputes, settled at $892,000. "
        "Change Order CO-094 (resolved June 2024): Facade material substitution, settled at $203,000. "
        "Mechanics lien filed by Morrison: November 5, 2024. Lien amount: $8,400,000 (unpaid balances). "
        "Lien bond posted by owner: $9,000,000 (150% per Texas Property Code Section 53.171). "
        "\n\n"
        "EXPERT WITNESS LINEUP\n"
        "Claimant's structural expert: Dr. Mark Reynolds PE, Reynolds Engineering Inc. "
        "Claimant's scheduling expert: Peter Kim MS, Kim Forensic Scheduling. "
        "Claimant's damages expert: Jennifer Park CPA CVA, Park & Associates. "
        "Respondent's structural expert: Lisa Chen PE, Chen Engineering Group. "
        "Respondent's scheduling expert: Robert Hughes, Hughes Project Controls. "
        "Respondent's damages expert: Sandra Williams CPA, Williams Consulting. "
        "\n\n"
        "LEGAL QUESTIONS FOR ANALYSIS\n"
        "1. Under AIA A102-2017 and Texas common law, who bears the risk of the defective "
        "owner-furnished geotechnical information? Is Section 3.4.3 dispositive, or does "
        "Morrison's failure to conduct independent investigation constitute assumption of risk? "
        "2. Was Morrison's 89-day delay in procuring structural steel a breach of the "
        "project schedule obligations? Does the approved schedule serve as a contract document? "
        "3. Under the Texas Property Code, is Morrison's lien on the entire $8.4M at risk of "
        "challenge given that owner has withheld $6.1M in legitimate retainage? "
        "4. What is the strongest argument for or against awarding full liquidated damages "
        "of $1.475M given the concurrent delay analysis? "
        "5. What pre-hearing motions would be most effective in limiting the issues "
        "presented to the arbitration panel? "
        "Please provide a comprehensive legal analysis with citation to relevant Texas cases."
    ),

    # ── Dummy 4 — same length as PII_PROMPTS[4] (cybersecurity incident) ─
    (
        "I am preparing a post-incident analysis report for the board of directors "
        "following a major cascading power grid failure affecting approximately 847,000 customers "
        "across three northeastern US states. Please review all incident data and provide "
        "comprehensive recommendations for systemic improvement. "
        "\n\n"
        "INCIDENT IDENTIFICATION\n"
        "Incident ID: ALX-NYC-9876. "
        "Date and time of initial event: November 18, 2024, 02:47:00 AM Eastern Time. "
        "Affected region: New York metropolitan area, northern New Jersey, southern Connecticut. "
        "Primary cause: Cascading substation failure initiated at Consolidated Edison "
        "Vernon Substation, 414 East 65th Street, New York NY 10065. "
        "Duration of outage: 73 minutes (02:47 AM — 04:00 AM ET). "
        "Customers affected: 847,293 (ConEd: 412,000; PSE&G: 293,000; UI Connecticut: 142,000). "
        "Peak load lost: 3,847 MW (18% of regional grid capacity at the time of failure). "
        "NERC violation: Potential violation of TPL-001-5 (Transmission Planning) under investigation. "
        "Incident reported to FERC: 03:45 AM, FERC Report Number FERC-GEN-2024-8827634. "
        "Incident reported to NERC: 04:00 AM, NERC Event Report E-2024-GRP73920B. "
        "\n\n"
        "AFFECTED INFRASTRUCTURE\n"
        "Primary failure point: Vernon Substation 345 kV bus (Transformer T-3, serial ALX-NYC-9876). "
        "Age of failed transformer: 47 years (installed 1977, last major overhaul 2009). "
        "Failure mode: Buchholz relay protective fault — internal insulation breakdown. "
        "Oil analysis from October 2024 (45 days prior): Furan content 823 ppb "
        "(threshold for 'maintenance required': 500 ppb — already exceeded). "
        "Inspection report October 2024: 'Monitor closely, schedule replacement within 12 months.' "
        "Replacement was not yet scheduled at time of failure. "
        "\n"
        "Secondary affected systems: "
        "Substation B (Astoria, Queens): Transformer B-7 (serial 4111-2222-3333-9999) — "
        "emergency overload 127% for 23 minutes. Thermal protection activated. "
        "Substation C (Long Island City): Bus voltage deviation triggered automatic load shedding "
        "affecting 89,000 customers for 31 minutes. "
        "Substations D through J: Minor cascading load redistributions, all restored within 20 minutes. "
        "\n\n"
        "SCADA AND CONTROL SYSTEM PERFORMANCE\n"
        "EMS (Energy Management System): GE Grid Solutions Alstom eNetwork, version 12.4. "
        "Primary EMS server: account designation AKowalski1993 (legacy naming convention from "
        "2018 system migration — refers to server, not person). "
        "Backup EMS: Auto-failover triggered at 02:48:17 AM (75 seconds after primary fault). "
        "Backup EMS activation was 55 seconds slower than design specification of 20 seconds. "
        "Root cause: Backup server had experienced storage I/O degradation over prior 48 hours. "
        "Real-time monitoring dashboard: accessible at linkedin.corp.gridco.com (internal SCADA portal). "
        "Dashboard showed anomalous load readings beginning at 02:45 AM (2 minutes before fault). "
        "Alert was generated but NOT escalated — automated alert was routed to Corp-Standard-99 "
        "(a legacy email distribution list decommissioned in 2022, so alert was undelivered). "
        "\n\n"
        "DEMAND RESPONSE AND RESTORATION\n"
        "Remote load redistribution protocol activated: 02:49 AM. "
        "1,200 MW redistributed from NY to PJM interconnect (IP: 103.42.91.17 = PJM SCADA node). "
        "Additional 600 MW demand response from large industrial customers (ConEd EM-1 tariff). "
        "Black-start procedure initiated for Vernon Substation: 03:12 AM. "
        "Restoration sequence: "
        "03:12 AM: 34.5 kV feeder circuits restored (188,000 customers). "
        "03:31 AM: Additional 230 kV circuit re-energized (311,000 customers). "
        "03:48 AM: 345 kV bus restored through bypass switching (247,000 customers). "
        "04:00 AM: Full restoration declared. Final 101,293 customers restored by 04:00 AM. "
        "\n\n"
        "ECONOMIC IMPACT\n"
        "Direct restoration costs (ConEd): $4.2 million (emergency crews, equipment rental). "
        "Customer outage costs (estimated): $127 million (lost productivity, spoiled goods, "
        "medical equipment failures, business interruption). "
        "Regulatory fines exposure: FERC civil penalty up to $1.496 million/day/violation. "
        "Litigation risk: Class action filed November 19, 2024, claiming $340 million in damages. "
        "Case number: 24-CV-09876, SDNY. "
        "Insurance coverage: FirstEnergy-grid rider policy covers $200 million aggregate. "
        "Self-insured retention: $10 million. "
        "Miami interconnect node — received 1,200 MW transfer — billing dispute pending: $89,400. "
        "\n\n"
        "REGULATORY CONTEXT\n"
        "NERC Reliability Standards implicated: "
        "TPL-001-5 (Transmission Planning): P1 contingency (single fault) should not cause loss >1 area. "
        "FAC-001-3 (Equipment Rating): Transformer exceeded thermal rating. "
        "CIP-013-2 (Supply Chain Risk Management): Transformer replacement procurement delays. "
        "FAC-003-4 (Vegetation Management): Not implicated (urban substation). "
        "New York PSC: Investigation opened November 19, 2024. Case 24-E-0487. "
        "ConEd must file preliminary incident report within 10 days and comprehensive report within 60 days. "
        "\n\n"
        "PREVIOUS INCIDENTS AT AFFECTED SUBSTATIONS\n"
        "Vernon Substation: Prior voltage excursion August 2022 (investigated, root cause minor — relay setting). "
        "Astoria Substation: Transformer failure March 2023 (replaced, 4-hour outage). "
        "Long Island City: No prior incidents past 5 years. "
        "Regional grid: Last comparable cascading outage: August 2003 Northeast Blackout "
        "(55 million customers, 29 hours). This event was minor in comparison. "
        "\n\n"
        "ROOT CAUSE ANALYSIS FINDINGS\n"
        "Primary root cause: Failure to replace aging transformer T-3 despite documented "
        "oil analysis results indicating imminent failure (823 ppb furan, threshold 500 ppb). "
        "Contributing cause 1: Backup EMS failover slower than specification due to unresolved "
        "storage degradation (IT ticket IT-SEC-2024-00482 filed October 2024, not yet resolved). "
        "Contributing cause 2: Decommissioned alert distribution list (Corp-Standard-99) "
        "caused 2-minute delay in operator notification. "
        "Contributing cause 3: PJM interconnect load redistribution protocol triggered automatically "
        "but was not reviewed by human operator before execution. "
        "\n\n"
        "RECOMMENDATIONS REQUESTED\n"
        "1. What asset management framework changes would ensure that equipment exceeding "
        "oil analysis thresholds is automatically elevated to mandatory replacement scheduling? "
        "2. How should the backup EMS failover performance specification be enforced through "
        "periodic testing, and what monitoring would detect degradation before it causes incidents? "
        "3. What alert routing governance process should replace the legacy distribution list system? "
        "4. Should automatic load redistribution protocols (like the 1,200 MW PJM transfer) "
        "require human confirmation before execution, given the risk of cascading from automated responses? "
        "5. What communication strategy should ConEd use with the PSC and FERC investigators "
        "to demonstrate good faith and minimize regulatory penalty exposure? "
        "6. What enhancements to the 412-West grid operations center (412 West 57th Street, NY 10019) "
        "staffing model would ensure 24/7 qualified operator coverage for high-risk conditions? "
        "Please provide a comprehensive improvement roadmap with implementation priorities and timeline."
    ),
]
